name: Deploy CoffeeShop App to Azure VM

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.0.x'

    - name: Build & Publish Project
      run: dotnet publish CoffeeShop/CoffeeShop.csproj -c Release -o ./publish

    - name: Stop Web App Service before file copy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 70.153.184.194
        username: lhkadmin
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          sudo systemctl stop coffeeshop || true

    - name: Copy compiled binaries to Azure VM via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 70.153.184.194
        username: lhkadmin
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        source: "publish/*"
        target: "~/coffeeshop_web"
        strip_prefix: "publish"

    - name: Start Web App Service on Both VMs
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 70.153.184.194
        username: lhkadmin
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          cp -rf ~/coffeeshop_web/publish/* ~/coffeeshop_web/ || true
          sudo systemctl restart coffeeshop
          rsync -avz --exclude 'app.log' ~/coffeeshop_web/ lhkadmin@172.16.0.5:~/coffeeshop_web/ || true
          ssh -o StrictHostKeyChecking=no lhkadmin@172.16.0.5 "sudo systemctl restart coffeeshop" || true

